=== BloodyDawn/Unity/l2junity-gameserver/dist/game/data/xsd/spawns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="npc">
		<xs:sequence>
			<xs:element name="parameters" minOccurs="0" maxOccurs="1" type="parameters" />
			<xs:element name="minions" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="minion" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:attribute type="xs:positiveInteger" name="id" use="optional" />
								<xs:attribute type="xs:byte" name="count" use="optional" />
								<xs:attribute type="xs:string" name="respawnTime" use="optional" />
								<xs:attribute type="xs:string" name="randomRespawn" use="optional" />
								<xs:attribute type="xs:nonNegativeInteger" name="weightpoint" use="optional" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="locations" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="location" maxOccurs="unbounded" minOccurs="0">
							<xs:complexType>
								<xs:attribute type="xs:integer" name="x" use="required" />
								<xs:attribute type="xs:integer" name="y" use="required" />
								<xs:attribute type="xs:integer" name="z" use="required" />
								<xs:attribute type="xs:integer" name="heading" use="optional" />
								<xs:attribute type="xs:double" name="chance" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:positiveInteger" name="id" use="optional" />
		<xs:attribute type="xs:string" name="zone" use="optional" />
		<xs:attribute type="xs:positiveInteger" name="count" use="optional" />
		<xs:attribute type="xs:string" name="respawnTime" use="optional" />
		<xs:attribute type="xs:string" name="respawnRandom" use="optional" />
		<xs:attribute type="xs:integer" name="x" use="optional" />
		<xs:attribute type="xs:integer" name="y" use="optional" />
		<xs:attribute type="xs:integer" name="z" use="optional" />
		<xs:attribute type="xs:integer" name="heading" use="optional" />
	</xs:complexType>

	<xs:complexType name="parameters">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="param">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="value" type="xs:string" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="skill">
				<xs:complexType>
					<xs:attribute name="name" type="xs:token" use="required" />
					<xs:attribute name="id" type="xs:positiveInteger" use="required" />
					<xs:attribute name="level" type="xs:positiveInteger" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="minions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="id" type="xs:positiveInteger" use="required" />
								<xs:attribute name="count" type="xs:positiveInteger" use="required" />
								<xs:attribute name="respawnTime" type="xs:nonNegativeInteger" use="required" />
								<xs:attribute name="weightPoint" type="xs:integer" use="required" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="name" type="xs:token" use="required" />
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="spawn" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="parameters" minOccurs="0" maxOccurs="1" type="parameters" />
							<xs:element name="npc" minOccurs="0" maxOccurs="unbounded" type="npc" />
							<xs:element name="group" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="npc" maxOccurs="unbounded" minOccurs="0" type="npc" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="spawnByDefault" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="name" use="optional" />
						<xs:attribute type="xs:string" name="ai" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BloodyDawn/Unity/l2junity-gameserver/dist/game/data/spawns/Magmeld/FairySettlement.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="FairySettlement" ai="DayNightSpawns">
		<group>
			<npc id="30370" x="215664" y="80870" z="824" heading="33960" respawnTime="60sec" /> <!-- Nerupa -->
			<npc id="32921" x="214508" y="79668" z="824" heading="14514" respawnTime="60sec" /> <!-- Fairy Citizen -->
			<npc id="33566" x="214341" y="79639" z="824" heading="7699" respawnTime="60sec" /> <!-- Hermuncus' Minion -->
			<npc id="32916" x="215136" y="80267" z="816" heading="2859" respawnTime="60sec" /> <!-- Large Wisp -->
			<npc id="32916" x="214813" y="80620" z="816" heading="42137" respawnTime="60sec" /> <!-- Large Wisp -->
			<npc id="32916" x="214881" y="80682" z="816" heading="31316" respawnTime="60sec" /> <!-- Large Wisp -->
			<npc id="32916" x="214666" y="80261" z="816" heading="23345" respawnTime="60sec" /> <!-- Large Wisp -->
			<npc id="32916" x="215129" y="80493" z="848" heading="49371" respawnTime="60sec" /> <!-- Large Wisp -->
			<npc id="32916" x="215040" y="80404" z="816" heading="22056" respawnTime="60sec" /> <!-- Large Wisp -->
			<npc id="32916" x="215148" y="80270" z="816" heading="55344" respawnTime="60sec" /> <!-- Large Wisp -->
			<npc id="32916" x="215116" y="80431" z="816" heading="9461" respawnTime="60sec" /> <!-- Large Wisp -->			
		</group>
	</spawn>
</list>

=== BloodyDawn/Unity/l2junity-gameserver/dist/game/data/spawns/old/21_18.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/spawns.xsd">
	<spawn name="21_18">
		<group>
			<npc id="31845" x="35396" y="13532" z="-3440" respawnTime="60sec" /> <!-- Bloody Pixy -->
			<npc id="31845" x="37440" y="8438" z="-3232" respawnTime="60sec" /> <!-- Bloody Pixy -->
			<npc id="20555" x="61156" y="28189" z="-3696"  heading="14279" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="63447" y="24214" z="-3792"  heading="53731" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="62510" y="24325" z="-3784"  heading="56434" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="61681" y="28497" z="-3712"  heading="23936" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="63320" y="21800" z="-3752" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="63172" y="19721" z="-3752" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="62284" y="19721" z="-3808"  heading="7110" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="62496" y="18464" z="-3696" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="60955" y="16400" z="-3880" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="62824" y="17696" z="-3696" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="61715" y="17476" z="-3800" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="61810" y="17476" z="-3768" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="60620" y="10798" z="-3656" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="60620" y="11986" z="-3720" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="60984" y="10798" z="-3640" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="60074" y="10996" z="-3704"  heading="5171" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="60551" y="30215" z="-3712"  heading="21740" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="61746" y="28720" z="-3736"  heading="49119" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="57480" y="30748" z="-3752" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20555" x="56472" y="30679" z="-3744" respawnTime="27sec" /> <!-- Giant Fungus -->
			<npc id="20558" x="59765" y="27069" z="-4192"  heading="61359" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="60200" y="21227" z="-4688"  heading="42731" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="61148" y="22158" z="-4200" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="60740" y="21963" z="-4432" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="58904" y="20013" z="-4976" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="57680" y="16822" z="-5072" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="57561" y="20412" z="-5288" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="58115" y="20261" z="-5224" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="58675" y="21682" z="-5184"  heading="35075" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="59616" y="17676" z="-4544" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="59616" y="17310" z="-4144" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="58546" y="11120" z="-4128" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="58546" y="10924" z="-4096" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="58956" y="10336" z="-3728" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="56442" y="12881" z="-5336" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="55506" y="13430" z="-5552" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="56910" y="13064" z="-5176" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="55506" y="14345" z="-5616" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="55014" y="18143" z="-5480" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="53326" y="18260" z="-5360" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="56069" y="17441" z="-5512" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="56954" y="18530" z="-5264" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="55379" y="22135" z="-5440"  heading="173" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="54953" y="20472" z="-5496"  heading="61087" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="55813" y="20666" z="-5448"  heading="40626" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="57324" y="20449" z="-5304"  heading="52672" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="56192" y="24372" z="-5280" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="56192" y="24638" z="-5304" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="59081" y="26110" z="-4536"  heading="56002" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="57793" y="25843" z="-4952"  heading="44240" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="56994" y="28731" z="-4680"  heading="29900" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="53516" y="27216" z="-5256"  heading="10419" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="54060" y="26859" z="-5184"  heading="56244" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="52876" y="24328" z="-5312"  heading="41928" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="52903" y="26712" z="-5184" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="53936" y="24335" z="-5352"  heading="58411" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="52904" y="16973" z="-5472"  heading="57139" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="45452" y="24792" z="-4888" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="43732" y="24428" z="-4704" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="20558" x="44807" y="24428" z="-4984" respawnTime="27sec" /> <!-- Rotting tree -->
			<npc id="29015" x="43531" y="17094" z="-4392"  heading="3019" respawnTime="360sec" /> <!-- Richard -->
			<npc id="29015" x="43199" y="17004" z="-4392"  heading="31405" respawnTime="360sec" /> <!-- Richard -->
			<npc id="29015" x="43341" y="16527" z="-4392"  heading="54879" respawnTime="360sec" /> <!-- Richard -->
			<npc id="29015" x="43255" y="17641" z="-4392"  heading="36796" respawnTime="360sec" /> <!-- Richard -->
			<npc id="29015" x="43090" y="16054" z="-4392"  heading="43570" respawnTime="360sec" /> <!-- Richard -->
			<npc id="29017" x="43343" y="18890" z="-4320"  heading="33871" respawnTime="360sec" /> <!-- Riba -->
			<npc id="29017" x="44683" y="16938" z="-4392"  heading="20274" respawnTime="360sec" /> <!-- Riba -->
			<npc id="29017" x="45087" y="16644" z="-4392"  heading="27508" respawnTime="360sec" /> <!-- Riba -->
			<npc id="29017" x="44004" y="17969" z="-4392"  heading="2888" respawnTime="360sec" /> <!-- Riba -->
			<npc id="29017" x="43612" y="17300" z="-4392"  heading="45502" respawnTime="360sec" /> <!-- Riba -->
			<npc id="29017" x="45216" y="16508" z="-4368"  heading="31287" respawnTime="360sec" /> <!-- Riba -->
			<npc id="29018" x="43602" y="16055" z="-4392"  heading="51150" respawnTime="360sec" /> <!-- Riba Iren -->
			<npc id="29018" x="44681" y="18047" z="-4392"  heading="12257" respawnTime="360sec" /> <!-- Riba Iren -->
			<npc id="27166" x="63707" y="31164" z="-3736" respawnTime="180sec" /> <!-- Abyssal Jewel 2 -->
		</group>
	</spawn>
</list>
